steps:
  - label: ":railway_track: Choosing child pipelines"
    plugins:
      - chronotc/monorepo-diff#v2.2.0:
          diff: "git diff --name-only HEAD~1"
          watch:
            - path: "basic_counter/"
              config:
                label: ":pipeline: Building basic_counter"
                command: buildkite-agent pipeline upload basic_counter/.buildkite/build_and_deploy.yml