steps:
  - label: "Triggering pipelines in demo apps"
    plugins:
      - chronotc/monorepo-diff#v2.2.0:
          diff: "git diff --name-only HEAD~1"
          watch:
            - path: "basic_counter/"
              config:
                command: buildkite-agent pipeline upload basic_counter/.buildkite/build_and_deploy.yml