env:
  DOCKER_REPO: europe-docker.pkg.dev/vaxine/vaxineio-examples

agent:
  os: linux

steps:
  - label: ":railway_track: Choosing child pipelines"
    plugins:
      - chronotc/monorepo-diff#v2.2.0:
          diff: "git diff --name-only HEAD~1"
          watch:
            - path: "basic_counter/"
              config:
                group: ":rocket: Basic counter example"
                label: ":pipeline: Building basic_counter"
                command: buildkite-agent pipeline upload basic_counter/.buildkite/build_and_deploy.yml