env:
  REPO: europe-docker.pkg.dev/vaxine/vaxineio-examples
  IMAGE: basic_counter

steps:
  - label: ":whale: Build & push the docker container"
    command:
      - "export SHORTSHA=$(echo $BUILDKITE_COMMIT | head -c 7)"
      - "cd basic_counter && docker build -t $REPO/$IMAGE:latest -t $REPO/$IMAGE:$$SHORTSHA ."
      - "docker push $REPO/$IMAGE:$SHORTSHA"
      - "docker push $REPO/$IMAGE:latest"
